blank_issues_enabled: true
contact_links:
  - name: Feature requests and ideas
    url: In Construction
    about: Suggest an idea for this project
  - name: Questions
    url: In Construction
    about: Please ask and answer questions here
